### ISSUE TITLE
Allow rendering of form inputs for only a specified locales subset

### ISSUE THREAD

**Issue by petyots** [Propaganistas/Laravel-Translatable-Bootforms#1]
Hello, this function is not working properly, for example i have this code : 

```
{!! BootForm::open() -> action(route('admin::admin.pages.store')) -> post() !!}
            {!! TranslatableBootForm::text(trans('texts.title'),'title')
                    ->dataForLocale('bg', 'attributeName', 'attributeValue')
                    ->addClassForLocale('bg', 'addedClass') !!}
``` 

This code outputs fields for all of the locales available. I want only for the bg locale.Thanks in advance

BG is my default app language btw.

**Comment by Propaganistas** [comment]
Hi

I think you misinterpret the functionality of the `*ForLocale()` methods: they modify the output for the specified locale, but do not prevent them from rendering. Such feature isn't implemented yet.
