### ISSUE TITLE
Undefined index: name when TranslatableBootForm::open()->action('/url') is called

### ISSUE THREAD

**Issue by gerardojbaez** [Propaganistas/Laravel-Translatable-Bootforms#13]
When I open my form adding attributes I get a `FatalErrorException: Method Propaganistas\LaravelTranslatableBootForms\TranslatableBootForm::__toString() must not throw an exception`.

Calling `TranslatableBootForm::open()->action('/url')->render()` I get `Undefine index: name in propaganistas/laravel-translatable-bootforms/src/TranslatableBootForm.php line 403`. I've added `dd($this->arguments())` before the return and I get an empty array.

Opening the forms with no attributes or using `BootForm::open()->action('/url')` directly works perfectly.

**Comment by Propaganistas** [comment]
Thanks for reporting! That should do the trick. A new release is rolled out as well.
