### ISSUE TITLE
'form-group-class' config parameter is not used

### ISSUE THREAD

**Issue by matimalsub** [Propaganistas/Laravel-Translatable-Bootforms#15]
Setting `'form-group-class' => 'form-group-translation %locale'` value in config is not working.
For getting it to work - in file:
**TranslatableBootForm.php**
320: `$this->addMethod('addGroupClass', str_replace('%locale', $locale, 'form-group-translation'));`
should be:
320: `$this->addMethod('addGroupClass', str_replace('%locale', $locale, $this->config['form-group-class']));`

**Comment by Propaganistas** [comment]
Good catch. Thanks for reporting.
