### ISSUE TITLE
There is no errors on translatable field

### ISSUE THREAD

**Issue by vkuzmov** [Propaganistas/Laravel-Translatable-Bootforms#16]
I don't see the error on my translatable field. I have this:

```
3 locales: bg, en, ru

In the view:
{!! TranslatableBootForm::text('Name', 'name') !!}

Rules: 
'bg[name]' => 'required|max:255',
'en[name]' => 'required|max:255',
'ru[name]' => 'required|max:255',
```

When I submit the form, I'm redirected back with $errors bag, but there is no indication to user that some field's validation has failed (see http://bit.ly/2dBNSjL). 

-- --

If I switch to normal BootForm everything works as expected:

```
In the view:
{!! BootForm::text('Name', 'name') !!}

Rules: 
'name' => 'required|max:255',
```

When I submit the form I get this (see http://bit.ly/2ewjP1a).

Can anyone help me here?

**Comment by Propaganistas** [comment]
Your rules definitions are wrong. This is the correct format:

```php
'bg.name' => 'required|max:255',
'en.name' => 'required|max:255',
'ru.name' => 'required|max:255',
```

See [Laravel Docs - Validation](https://laravel.com/docs/master/validation#quick-writing-the-validation-logic) and scroll down to the "nested attributes" part.

**Comment by vkuzmov** [comment]
Thanks a lot :) it works now

**Comment by GeoSot** [comment]
Hello. Is there any way to do a more generic validation on the translatables?
par example: '*.name' => 'required|max:255', ???

The above does not work cause it messes with all the form items

But if the automated generator could be configed to generate items like trans[en][name] it could be validated from a rule like 'item.*.name'
