### ISSUE TITLE
Generic translatables validation - Allow custom name attribute format

### ISSUE THREAD

**Issue by GeoSot** [Propaganistas/Laravel-Translatable-Bootforms#18]
Hello. Is there any way to do a more generic validation on the translatables?
par example: '*.name' => 'required|max:255', ???

The above does not work cause it messes with all the form items

But if the automated generator could be configed to generate items like trans[en][name] it could be validated from a rule like 'item.*.name'

**Comment by Propaganistas** [comment]
I've rolled out a new release containing the feature you requested. Use the `%locale` placeholder when specifying the name, e.g.

```php
TranslatableBootform::text('My name', 'item.%locale.name')
```

Please update to `1.3.6`

**Comment by GeoSot** [comment]
Thanks for the quick response. 
(The last sentence sucked my happiness. )
