### ISSUE TITLE
PHP 5.5.9

### ISSUE THREAD

**Issue by sdebacker** [Propaganistas/Laravel-Translatable-Bootforms#2]
Hello,

For [TypiCMS](https://github.com/typicms/typicms), I’m switching to this package, because it's very good. But why requiring PHP 5.6 and not 5.5.9 like Laravel 5.x ?

Thank you

**Comment by Propaganistas** [comment]
Cool! You might want to notify dimsav for updating the readme of `laravel-translatable`.

I'm requiring PHP 5.6 because I've used the splat operator (`...`) for argument unpacking.
Feel free to submit a PR though to compatiblize back to 5.5.9.

**Comment by sdebacker** [comment]
I changed the order of add ons in the readme of laravel-translatable. Requiring PHP 5.6, it's not a big issue for me, I will make a PR if I have some time for it. Thank you.

**Comment by Propaganistas** [comment]
Support is added (999c536a975a0f974020bbae5b15cf2cd6ce2295).

**Comment by sdebacker** [comment]
Nice!
