### ISSUE TITLE
Disable or remove error default message on tag

### ISSUE THREAD

**Issue by A-Elwafa** [Propaganistas/Laravel-Translatable-Bootforms#21]
Hello again
I can't find away to remove the error message when i redirect with error message.
Is there away to remove it

`<div class="form-group {!! $errors->has('first_name') ? 'has-error' : '' !!}">
      <label for="first_name">First Name</label>
         <input type="text" class="form-control" id="first_name">
             //remove this line       {!! $errors->first('first_name', '<p class="help-block">:message</p>') !!}
           </div>`

**Comment by Propaganistas** [comment]
This is a question related to [BootForms](https://github.com/adamwathan/bootforms).

I guess you could try appending a nulled helpBlock method (`->helpBlock(null)`), but I never tried it myself. If this doesn't work out, please redirect your question to BootForms issue queue.
