### ISSUE TITLE
Update to Laravel 5.4

### ISSUE THREAD

**Issue by GeoSot** [Propaganistas/Laravel-Translatable-Bootforms#22]

**Comment by GeoSot** [comment]
Hello.
You have done a great work and thank you for this.


May i suggest you an update on Laravel 5.4?

On TranslatableBootFormsServiceProvider->register() the methods **share** and **getToken**
have been changed

https://laravel.com/docs/5.4/upgrade

**Comment by Propaganistas** [comment]
Thanks for the heads up. Please update to `1.3.7`.

**Comment by GeoSot** [comment]
another change needs on    "dimsav/laravel-translatable": "~5.0|~6.0|~7.0" in order to be updated

**Comment by Propaganistas** [comment]
There isn't any 7.0 tag:

https://github.com/dimsav/laravel-translatable/tags

**Comment by Propaganistas** [comment]
Now there is. New release has been tagged.
