### ISSUE TITLE
Compatibility with adamwathan/bootforms "^0.8.2"

### ISSUE THREAD

**Issue by anaisabel19886** [Propaganistas/Laravel-Translatable-Bootforms#24]
Hi, i've just composer updated a project with "propaganistas/laravel-translatable-bootforms": "~1.3", and "adamwathan/bootforms": "^0.8.2" (on composer.json) and now the labels for the translatable inputs aren't being escaped.

![translatable](https://user-images.githubusercontent.com/12087482/27838663-0e735c80-60e4-11e7-86ac-c45afe884d4b.png)

Will there be a fix, or I need to revert the update?

(thanks for a great package!)

**Comment by Propaganistas** [comment]
You should raise an issue in [adamwathan/form](https://github.com/adamwathan/form) for this. The latest release introduced escaping of `<label>` contents, converting the `<span>` definitions inside to actual text instead of parsable HTML:

class `AdamWathan\Form\Elements\Label`
```php
public function render()
    {
        $tags = [sprintf('<label%s>', $this->renderAttributes())];

        if ($this->labelBefore) {
            $tags[] = $this->escape($this->label);  // THESE LINES ARE THE CULPRITS
        }

        $tags[] = $this->renderElement();

        if (! $this->labelBefore) {
            $tags[] = $this->escape($this->label);  // THESE LINES ARE THE CULPRITS
        }

        $tags[] = '</label>';

        return implode($tags);
    }
```

**Comment by anaisabel19886** [comment]
Thank you, I will do so!

**Comment by rico** [comment]
@anaisabel19886 it seems version 1.3.9 of this package requires `adamwathan/form` / `adamwathan/bootforms` ^0.8 (where the escaping is not reverted). What package versions / combinations are you using to make that work? 
@Propaganistas since version 0.9 of `adamwathan/form` differs from the latest 0.8.x version only by this small change - can you update your package with a dependency of the `adamwathan` packages version `0.9`?

**Comment by anaisabel19886** [comment]
The version 0.9 change on adamwathan/form was made thanks to an issue I raised, as suggested by Propagandistas. 
[https://github.com/adamwathan/form/issues/121]

**Comment by Propaganistas** [comment]
See v[1.3.10](https://github.com/Propaganistas/Laravel-Translatable-Bootforms/releases/tag/1.3.10)
