### ISSUE TITLE
Grouping Form Inputs

### ISSUE THREAD

**Issue by haabnaseem** [Propaganistas/Laravel-Translatable-Bootforms#27]
Hi, Is there any way i can group form inputs by language ? 
Currently all inputs are listed without grouping

For Example: 

EN
-----
input 1
input 2 

RU
-----
input 1
input 2

**Comment by Propaganistas** [comment]
> To render a *form element only for some chosen locales*, explicitly call `renderLocale()` as the final method and pass the locale or an array of locales as the first parameter:
```php
TranslatableBootForm::text('Name','name')
                    ->renderLocale('en')
```

Loop your available languages

**Comment by haabnaseem** [comment]
Thank you,
what i did was looped available languages :)
