### ISSUE TITLE
Laravel 5 Validations

### ISSUE THREAD

**Issue by AEK-BKF** [Propaganistas/Laravel-Translatable-Bootforms#3]
Hi,
Thanks for this nice package,
I wonder how could I validate requests data if I use three locales ?
For example I've an attribute 'name' , using your package it will create three inputs 
en[name] ln[name] fr[name]
and I want to validate name with unique rule 
Thanks

**Comment by Propaganistas** [comment]
Hi

Each locale will be an array containing the corresponding inputs.
For example you might get something like this when running `$request->all()`:

```php
array(
   'non-translated-input' => 'value',
   'en' => array(
      'name' => 'English name',
      'translated-input' => 'English translation for input',
   ),
   'fr' => array(
      'name' => 'French name',
      'translated-input' => 'French translation for input',
   ),
)
```

So you would need array validation e.g. by looping the keys and checking if its value is an array and then apply the corresponding rule the inner key value.

**Comment by AEK-BKF** [comment]
Sorry I didn't understand your answer, 
here my code :

    public function translate(Request $request, $id)
     {

        $department = Department::findOrFail($id);
        $data = $request->all();                
        $v = Validator::make($data, $this->editTranslateRules($id));        
        if ($v->fails())
        {
            ...    
        } 
        else{ 
            $department->fill($data)->save();    
            ...                  
        } 
    }

     protected function editTranslateRules($id)
    {            
        return array( 
                      'name' => 'required|max:150|unique:department_translations,name,'.$id,
                      'description' => 'max:255',
                    );
    } 

So how can I apply your suggestion ?
Thanks a lot for your help

**Comment by Propaganistas** [comment]
```php
protected function editTranslateRules($id)
{
    $rules = array( 'description' => 'max:255' );
    $translationRules = array( 'name' => 'required|max:150|unique:department_translations,name,'.$id );
    
    // Add translation rules to rules array for each defined locale.
    foreach (config('translatable.locales') as $locale) {
        foreach ($translationRules as $key => $rule) {
            $rules["$locale.$key"] = $rule;
        }
    }

    return $rules;
} 
```
