### ISSUE TITLE
Bug Since the new version of Form package

### ISSUE THREAD

**Issue by sdebacker** [Propaganistas/Laravel-Translatable-Bootforms#7]
There is a new big bug that leave ML fields empty.
I suppose that the bug appeared in this commit: https://github.com/Propaganistas/Laravel-Translatable-Bootforms/commit/ebb14c8079cce0b77241f0e5d768c2a24fe81f9a

**Comment by Propaganistas** [comment]
This is indeed a remnant of a workaround attempt for #6.
Nice catch.
